"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import TYPE_CHECKING
from importlib import import_module
import builtins

if TYPE_CHECKING:
    from .accesstokenrequest import AccessTokenRequest, AccessTokenRequestTypedDict
    from .accountselectmodeenum import AccountSelectModeEnum
    from .autorefreshupdaterequest import (
        AutoRefreshUpdateRequest,
        AutoRefreshUpdateRequestTypedDict,
    )
    from .connectioncontextresponse import (
        ConnectionContextResponse,
        ConnectionContextResponseTypedDict,
    )
    from .connectionpublictokenexchangerequest import (
        ConnectionPublicTokenExchangeRequest,
        ConnectionPublicTokenExchangeRequestTypedDict,
    )
    from .connectionpublictokenexchangeresponse import (
        ConnectionPublicTokenExchangeResponse,
        ConnectionPublicTokenExchangeResponseTypedDict,
    )
    from .connectivitystatusenum import ConnectivityStatusEnum
    from .documentinfo import DocumentInfo, DocumentInfoTypedDict
    from .documentlistresponse import (
        DocumentListResponse,
        DocumentListResponseTypedDict,
    )
    from .entity import Entity, EntityTypedDict
    from .errorcategoryenum import ErrorCategoryEnum
    from .errorcodeenum import ErrorCodeEnum
    from .fieldtypeenum import FieldTypeEnum
    from .getconnectionaccountsrequestaccount import (
        GetConnectionAccountsRequestAccount,
        GetConnectionAccountsRequestAccountTypedDict,
    )
    from .getconnectionaccountsresponse import (
        GetConnectionAccountsResponse,
        GetConnectionAccountsResponseTypedDict,
    )
    from .getconnectionaccountsresponseaccount import (
        GetConnectionAccountsResponseAccount,
        GetConnectionAccountsResponseAccountTypedDict,
    )
    from .invalidateaccesstokenresponse import (
        InvalidateAccessTokenResponse,
        InvalidateAccessTokenResponseTypedDict,
    )
    from .jobresponse import JobResponse, JobResponseTypedDict
    from .languageenum import LanguageEnum
    from .linkaccountlistresponse import (
        LinkAccountListResponse,
        LinkAccountListResponseTypedDict,
    )
    from .linkaccountlistresponseaccountitem import (
        LinkAccountListResponseAccountItem,
        LinkAccountListResponseAccountItemTypedDict,
    )
    from .linkaccountselectrequest import (
        LinkAccountSelectRequest,
        LinkAccountSelectRequestTypedDict,
    )
    from .linkclientinforesponse import (
        LinkClientInfoResponse,
        LinkClientInfoResponseTypedDict,
        Mode,
        UpdateMode,
        UpdateModeTypedDict,
    )
    from .linkconnectionstatusresponse import (
        LinkConnectionStatusResponse,
        LinkConnectionStatusResponseTypedDict,
    )
    from .linkconnectionstatusresponseenum import LinkConnectionStatusResponseEnum
    from .linkconnectrequest import LinkConnectRequest, LinkConnectRequestTypedDict
    from .linkconnectrequestfield import (
        LinkConnectRequestField,
        LinkConnectRequestFieldTypedDict,
    )
    from .linkconnectresponse import LinkConnectResponse, LinkConnectResponseTypedDict
    from .linksourcesrequest import LinkSourcesRequest, LinkSourcesRequestTypedDict
    from .linksourcesresponse import LinkSourcesResponse, LinkSourcesResponseTypedDict
    from .linksourcesresponsesource import (
        LinkSourcesResponseSource,
        LinkSourcesResponseSourceTypedDict,
    )
    from .linksourcesresponsesourcefield import (
        LinkSourcesResponseSourceField,
        LinkSourcesResponseSourceFieldTypedDict,
    )
    from .linktokencreaterequest import (
        LinkTokenCreateRequest,
        LinkTokenCreateRequestBetaSourceStatus,
        LinkTokenCreateRequestLanguage,
        LinkTokenCreateRequestTypedDict,
        ParsingMethod,
        Update,
        UpdateTypedDict,
    )
    from .linktokencreaterequestupdatemodeenum import (
        LinkTokenCreateRequestUpdateModeEnum,
    )
    from .linktokengetresponse import (
        LinkTokenGetResponse,
        LinkTokenGetResponseBetaSourceStatus,
        LinkTokenGetResponseLanguage,
        LinkTokenGetResponseTypedDict,
    )
    from .linktokenrequestresponse import (
        LinkTokenRequestResponse,
        LinkTokenRequestResponseTypedDict,
    )
    from .mfaanswerrequest import MfaAnswerRequest, MfaAnswerRequestTypedDict
    from .post_jobs_documents_fileop import (
        PostJobsDocumentsFileResponse,
        PostJobsDocumentsFileResponseTypedDict,
    )
    from .post_jobs_documents_listop import (
        PostJobsDocumentsListRequest,
        PostJobsDocumentsListRequestTypedDict,
    )
    from .post_jobs_submitop import (
        PostJobsSubmitRequest,
        PostJobsSubmitRequestTypedDict,
    )
    from .provider import Provider, ProviderTypedDict
    from .rawdocumentrequest import RawDocumentRequest, RawDocumentRequestTypedDict
    from .refreshconnectionrequest import (
        RefreshConnectionRequest,
        RefreshConnectionRequestTypedDict,
    )
    from .scrapingstatusenum import ScrapingStatusEnum
    from .security import Security, SecurityTypedDict
    from .securityquestionanswersaverequest import (
        SecurityQuestionAnswerSaveRequest,
        SecurityQuestionAnswerSaveRequestTypedDict,
    )
    from .securityquestionresponse import (
        SecurityQuestionResponse,
        SecurityQuestionResponseTypedDict,
    )
    from .selectconnectionaccountsrequest import (
        SelectConnectionAccountsRequest,
        SelectConnectionAccountsRequestTypedDict,
    )
    from .webhookupdaterequest import (
        WebhookUpdateRequest,
        WebhookUpdateRequestTypedDict,
    )

__all__ = [
    "AccessTokenRequest",
    "AccessTokenRequestTypedDict",
    "AccountSelectModeEnum",
    "AutoRefreshUpdateRequest",
    "AutoRefreshUpdateRequestTypedDict",
    "ConnectionContextResponse",
    "ConnectionContextResponseTypedDict",
    "ConnectionPublicTokenExchangeRequest",
    "ConnectionPublicTokenExchangeRequestTypedDict",
    "ConnectionPublicTokenExchangeResponse",
    "ConnectionPublicTokenExchangeResponseTypedDict",
    "ConnectivityStatusEnum",
    "DocumentInfo",
    "DocumentInfoTypedDict",
    "DocumentListResponse",
    "DocumentListResponseTypedDict",
    "Entity",
    "EntityTypedDict",
    "ErrorCategoryEnum",
    "ErrorCodeEnum",
    "FieldTypeEnum",
    "GetConnectionAccountsRequestAccount",
    "GetConnectionAccountsRequestAccountTypedDict",
    "GetConnectionAccountsResponse",
    "GetConnectionAccountsResponseAccount",
    "GetConnectionAccountsResponseAccountTypedDict",
    "GetConnectionAccountsResponseTypedDict",
    "InvalidateAccessTokenResponse",
    "InvalidateAccessTokenResponseTypedDict",
    "JobResponse",
    "JobResponseTypedDict",
    "LanguageEnum",
    "LinkAccountListResponse",
    "LinkAccountListResponseAccountItem",
    "LinkAccountListResponseAccountItemTypedDict",
    "LinkAccountListResponseTypedDict",
    "LinkAccountSelectRequest",
    "LinkAccountSelectRequestTypedDict",
    "LinkClientInfoResponse",
    "LinkClientInfoResponseTypedDict",
    "LinkConnectRequest",
    "LinkConnectRequestField",
    "LinkConnectRequestFieldTypedDict",
    "LinkConnectRequestTypedDict",
    "LinkConnectResponse",
    "LinkConnectResponseTypedDict",
    "LinkConnectionStatusResponse",
    "LinkConnectionStatusResponseEnum",
    "LinkConnectionStatusResponseTypedDict",
    "LinkSourcesRequest",
    "LinkSourcesRequestTypedDict",
    "LinkSourcesResponse",
    "LinkSourcesResponseSource",
    "LinkSourcesResponseSourceField",
    "LinkSourcesResponseSourceFieldTypedDict",
    "LinkSourcesResponseSourceTypedDict",
    "LinkSourcesResponseTypedDict",
    "LinkTokenCreateRequest",
    "LinkTokenCreateRequestBetaSourceStatus",
    "LinkTokenCreateRequestLanguage",
    "LinkTokenCreateRequestTypedDict",
    "LinkTokenCreateRequestUpdateModeEnum",
    "LinkTokenGetResponse",
    "LinkTokenGetResponseBetaSourceStatus",
    "LinkTokenGetResponseLanguage",
    "LinkTokenGetResponseTypedDict",
    "LinkTokenRequestResponse",
    "LinkTokenRequestResponseTypedDict",
    "MfaAnswerRequest",
    "MfaAnswerRequestTypedDict",
    "Mode",
    "ParsingMethod",
    "PostJobsDocumentsFileResponse",
    "PostJobsDocumentsFileResponseTypedDict",
    "PostJobsDocumentsListRequest",
    "PostJobsDocumentsListRequestTypedDict",
    "PostJobsSubmitRequest",
    "PostJobsSubmitRequestTypedDict",
    "Provider",
    "ProviderTypedDict",
    "RawDocumentRequest",
    "RawDocumentRequestTypedDict",
    "RefreshConnectionRequest",
    "RefreshConnectionRequestTypedDict",
    "ScrapingStatusEnum",
    "Security",
    "SecurityQuestionAnswerSaveRequest",
    "SecurityQuestionAnswerSaveRequestTypedDict",
    "SecurityQuestionResponse",
    "SecurityQuestionResponseTypedDict",
    "SecurityTypedDict",
    "SelectConnectionAccountsRequest",
    "SelectConnectionAccountsRequestTypedDict",
    "Update",
    "UpdateMode",
    "UpdateModeTypedDict",
    "UpdateTypedDict",
    "WebhookUpdateRequest",
    "WebhookUpdateRequestTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "AccessTokenRequest": ".accesstokenrequest",
    "AccessTokenRequestTypedDict": ".accesstokenrequest",
    "AccountSelectModeEnum": ".accountselectmodeenum",
    "AutoRefreshUpdateRequest": ".autorefreshupdaterequest",
    "AutoRefreshUpdateRequestTypedDict": ".autorefreshupdaterequest",
    "ConnectionContextResponse": ".connectioncontextresponse",
    "ConnectionContextResponseTypedDict": ".connectioncontextresponse",
    "ConnectionPublicTokenExchangeRequest": ".connectionpublictokenexchangerequest",
    "ConnectionPublicTokenExchangeRequestTypedDict": ".connectionpublictokenexchangerequest",
    "ConnectionPublicTokenExchangeResponse": ".connectionpublictokenexchangeresponse",
    "ConnectionPublicTokenExchangeResponseTypedDict": ".connectionpublictokenexchangeresponse",
    "ConnectivityStatusEnum": ".connectivitystatusenum",
    "DocumentInfo": ".documentinfo",
    "DocumentInfoTypedDict": ".documentinfo",
    "DocumentListResponse": ".documentlistresponse",
    "DocumentListResponseTypedDict": ".documentlistresponse",
    "Entity": ".entity",
    "EntityTypedDict": ".entity",
    "ErrorCategoryEnum": ".errorcategoryenum",
    "ErrorCodeEnum": ".errorcodeenum",
    "FieldTypeEnum": ".fieldtypeenum",
    "GetConnectionAccountsRequestAccount": ".getconnectionaccountsrequestaccount",
    "GetConnectionAccountsRequestAccountTypedDict": ".getconnectionaccountsrequestaccount",
    "GetConnectionAccountsResponse": ".getconnectionaccountsresponse",
    "GetConnectionAccountsResponseTypedDict": ".getconnectionaccountsresponse",
    "GetConnectionAccountsResponseAccount": ".getconnectionaccountsresponseaccount",
    "GetConnectionAccountsResponseAccountTypedDict": ".getconnectionaccountsresponseaccount",
    "InvalidateAccessTokenResponse": ".invalidateaccesstokenresponse",
    "InvalidateAccessTokenResponseTypedDict": ".invalidateaccesstokenresponse",
    "JobResponse": ".jobresponse",
    "JobResponseTypedDict": ".jobresponse",
    "LanguageEnum": ".languageenum",
    "LinkAccountListResponse": ".linkaccountlistresponse",
    "LinkAccountListResponseTypedDict": ".linkaccountlistresponse",
    "LinkAccountListResponseAccountItem": ".linkaccountlistresponseaccountitem",
    "LinkAccountListResponseAccountItemTypedDict": ".linkaccountlistresponseaccountitem",
    "LinkAccountSelectRequest": ".linkaccountselectrequest",
    "LinkAccountSelectRequestTypedDict": ".linkaccountselectrequest",
    "LinkClientInfoResponse": ".linkclientinforesponse",
    "LinkClientInfoResponseTypedDict": ".linkclientinforesponse",
    "Mode": ".linkclientinforesponse",
    "UpdateMode": ".linkclientinforesponse",
    "UpdateModeTypedDict": ".linkclientinforesponse",
    "LinkConnectionStatusResponse": ".linkconnectionstatusresponse",
    "LinkConnectionStatusResponseTypedDict": ".linkconnectionstatusresponse",
    "LinkConnectionStatusResponseEnum": ".linkconnectionstatusresponseenum",
    "LinkConnectRequest": ".linkconnectrequest",
    "LinkConnectRequestTypedDict": ".linkconnectrequest",
    "LinkConnectRequestField": ".linkconnectrequestfield",
    "LinkConnectRequestFieldTypedDict": ".linkconnectrequestfield",
    "LinkConnectResponse": ".linkconnectresponse",
    "LinkConnectResponseTypedDict": ".linkconnectresponse",
    "LinkSourcesRequest": ".linksourcesrequest",
    "LinkSourcesRequestTypedDict": ".linksourcesrequest",
    "LinkSourcesResponse": ".linksourcesresponse",
    "LinkSourcesResponseTypedDict": ".linksourcesresponse",
    "LinkSourcesResponseSource": ".linksourcesresponsesource",
    "LinkSourcesResponseSourceTypedDict": ".linksourcesresponsesource",
    "LinkSourcesResponseSourceField": ".linksourcesresponsesourcefield",
    "LinkSourcesResponseSourceFieldTypedDict": ".linksourcesresponsesourcefield",
    "LinkTokenCreateRequest": ".linktokencreaterequest",
    "LinkTokenCreateRequestBetaSourceStatus": ".linktokencreaterequest",
    "LinkTokenCreateRequestLanguage": ".linktokencreaterequest",
    "LinkTokenCreateRequestTypedDict": ".linktokencreaterequest",
    "ParsingMethod": ".linktokencreaterequest",
    "Update": ".linktokencreaterequest",
    "UpdateTypedDict": ".linktokencreaterequest",
    "LinkTokenCreateRequestUpdateModeEnum": ".linktokencreaterequestupdatemodeenum",
    "LinkTokenGetResponse": ".linktokengetresponse",
    "LinkTokenGetResponseBetaSourceStatus": ".linktokengetresponse",
    "LinkTokenGetResponseLanguage": ".linktokengetresponse",
    "LinkTokenGetResponseTypedDict": ".linktokengetresponse",
    "LinkTokenRequestResponse": ".linktokenrequestresponse",
    "LinkTokenRequestResponseTypedDict": ".linktokenrequestresponse",
    "MfaAnswerRequest": ".mfaanswerrequest",
    "MfaAnswerRequestTypedDict": ".mfaanswerrequest",
    "PostJobsDocumentsFileResponse": ".post_jobs_documents_fileop",
    "PostJobsDocumentsFileResponseTypedDict": ".post_jobs_documents_fileop",
    "PostJobsDocumentsListRequest": ".post_jobs_documents_listop",
    "PostJobsDocumentsListRequestTypedDict": ".post_jobs_documents_listop",
    "PostJobsSubmitRequest": ".post_jobs_submitop",
    "PostJobsSubmitRequestTypedDict": ".post_jobs_submitop",
    "Provider": ".provider",
    "ProviderTypedDict": ".provider",
    "RawDocumentRequest": ".rawdocumentrequest",
    "RawDocumentRequestTypedDict": ".rawdocumentrequest",
    "RefreshConnectionRequest": ".refreshconnectionrequest",
    "RefreshConnectionRequestTypedDict": ".refreshconnectionrequest",
    "ScrapingStatusEnum": ".scrapingstatusenum",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "SecurityQuestionAnswerSaveRequest": ".securityquestionanswersaverequest",
    "SecurityQuestionAnswerSaveRequestTypedDict": ".securityquestionanswersaverequest",
    "SecurityQuestionResponse": ".securityquestionresponse",
    "SecurityQuestionResponseTypedDict": ".securityquestionresponse",
    "SelectConnectionAccountsRequest": ".selectconnectionaccountsrequest",
    "SelectConnectionAccountsRequestTypedDict": ".selectconnectionaccountsrequest",
    "WebhookUpdateRequest": ".webhookupdaterequest",
    "WebhookUpdateRequestTypedDict": ".webhookupdaterequest",
}


def __getattr__(attr_name: str) -> object:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__} "
        )

    try:
        module = import_module(module_name, __package__)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = builtins.list(_dynamic_imports.keys())
    return builtins.sorted(lazy_attrs)
