"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from deck_sdk.types import BaseModel
from typing_extensions import TypedDict


class AutoRefreshUpdateRequestTypedDict(TypedDict):
    access_token: str
    r"""The access token associated with the Item data is being requested for"""
    auto_refresh: bool
    r"""Flag to toggle the automatic refresh when new connection's data is found"""


class AutoRefreshUpdateRequest(BaseModel):
    access_token: str
    r"""The access token associated with the Item data is being requested for"""

    auto_refresh: bool
    r"""Flag to toggle the automatic refresh when new connection's data is found"""
