"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .connectivitystatusenum import ConnectivityStatusEnum
from .entity import Entity, EntityTypedDict
from .provider import Provider, ProviderTypedDict
from .scrapingstatusenum import ScrapingStatusEnum
from datetime import datetime
from deck_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ConnectionContextResponseTypedDict(TypedDict):
    provider: ProviderTypedDict
    r"""The data source associated to this connectiond"""
    entities: List[EntityTypedDict]
    r"""A list of entities associated with this connection."""
    connection_id: NotRequired[str]
    r"""The Deck Connection ID associated with the access token data being requested"""
    connection_status: NotRequired[ConnectivityStatusEnum]
    r"""Represents the current connection health status between the system and the data source, such as Connected or Disconnected."""
    connection_status_timestamp: NotRequired[datetime]
    r"""The UTC timestamp of when the connectivity status was last updated."""
    connection_status_reason: NotRequired[ScrapingStatusEnum]
    r"""Represents the most recent scraping result for this connection, providing additional context to the connectivity status."""
    num_of_entities: NotRequired[int]
    r"""Represents the number of accounts."""


class ConnectionContextResponse(BaseModel):
    provider: Provider
    r"""The data source associated to this connectiond"""

    entities: List[Entity]
    r"""A list of entities associated with this connection."""

    connection_id: Optional[str] = None
    r"""The Deck Connection ID associated with the access token data being requested"""

    connection_status: Optional[ConnectivityStatusEnum] = None
    r"""Represents the current connection health status between the system and the data source, such as Connected or Disconnected."""

    connection_status_timestamp: Optional[datetime] = None
    r"""The UTC timestamp of when the connectivity status was last updated."""

    connection_status_reason: Optional[ScrapingStatusEnum] = None
    r"""Represents the most recent scraping result for this connection, providing additional context to the connectivity status."""

    num_of_entities: Optional[int] = None
    r"""Represents the number of accounts."""
