"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from deck_sdk.types import BaseModel
from typing_extensions import TypedDict


class ConnectionPublicTokenExchangeRequestTypedDict(TypedDict):
    public_token: str
    r"""Your public_token, obtained from the Link onSuccess callback"""


class ConnectionPublicTokenExchangeRequest(BaseModel):
    public_token: str
    r"""Your public_token, obtained from the Link onSuccess callback"""
