"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .linkconnectrequestfield import (
    LinkConnectRequestField,
    LinkConnectRequestFieldTypedDict,
)
from deck_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ConnectionPublicTokenExchangeResponseTypedDict(TypedDict):
    fields: List[LinkConnectRequestFieldTypedDict]
    r"""List of non-sensitive values provided from the Link session by the user"""
    access_token: NotRequired[str]
    r"""The access token associated with the connection data is being requested for"""
    connection_id: NotRequired[str]
    r"""The Deck Connection ID for the connection associated with the returned access token"""


class ConnectionPublicTokenExchangeResponse(BaseModel):
    fields: List[LinkConnectRequestField]
    r"""List of non-sensitive values provided from the Link session by the user"""

    access_token: Optional[str] = None
    r"""The access token associated with the connection data is being requested for"""

    connection_id: Optional[str] = None
    r"""The Deck Connection ID for the connection associated with the returned access token"""
