"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .documentinfo import DocumentInfo, DocumentInfoTypedDict
from deck_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class DocumentListResponseTypedDict(TypedDict):
    documents: List[DocumentInfoTypedDict]


class DocumentListResponse(BaseModel):
    documents: List[DocumentInfo]
