"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from deck_sdk.types import BaseModel
from typing_extensions import TypedDict


class EntityTypedDict(TypedDict):
    account_number: str


class Entity(BaseModel):
    account_number: str
