"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class FieldTypeEnum(str, Enum):
    TEXT = "Text"
    PASSWORD = "Password"
