"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .getconnectionaccountsresponseaccount import (
    GetConnectionAccountsResponseAccount,
    GetConnectionAccountsResponseAccountTypedDict,
)
from deck_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class GetConnectionAccountsResponseTypedDict(TypedDict):
    accounts: NotRequired[List[GetConnectionAccountsResponseAccountTypedDict]]


class GetConnectionAccountsResponse(BaseModel):
    accounts: Optional[List[GetConnectionAccountsResponseAccount]] = None
