"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from deck_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class InvalidateAccessTokenResponseTypedDict(TypedDict):
    new_access_token: NotRequired[str]
    r"""The access token associated with the connection data being requested"""


class InvalidateAccessTokenResponse(BaseModel):
    new_access_token: Optional[str] = None
    r"""The access token associated with the connection data being requested"""
