"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from deck_sdk.types import BaseModel
from typing_extensions import TypedDict


class JobResponseTypedDict(TypedDict):
    job_guid: str
    r"""The unique identifier of the job."""
    job_code: str
    r"""The code representing the type of job executed."""


class JobResponse(BaseModel):
    job_guid: str
    r"""The unique identifier of the job."""

    job_code: str
    r"""The code representing the type of job executed."""
