"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class LanguageEnum(str, Enum):
    EN = "EN"
    ES = "ES"
    FR = "FR"
    DE = "DE"
    IT = "IT"
    PT = "PT"
    NL = "NL"
    PL = "PL"
    SV = "SV"
    DA = "DA"
    NO = "NO"
    ET = "ET"
    LT = "LT"
    LV = "LV"
    RO = "RO"
