"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class LinkConnectionStatusResponseEnum(str, Enum):
    NEW = "New"
    CONNECTING = "Connecting"
    CONNECTED = "Connected"
    INVALID_CREDENTIALS = "InvalidCredentials"
    ERROR = "Error"
    MFA_METHOD_CHOICE = "MfaMethodChoice"
    MFA_QUESTION = "MfaQuestion"
    MFA_QUESTION_INVALID_ANSWER = "MfaQuestionInvalidAnswer"
    MFA_QUESTION_NO_ANSWER = "MfaQuestionNoAnswer"
    CAPTCHA = "Captcha"
    SECURITY_QUESTION = "SecurityQuestion"
    ACCOUNT_SELECTION = "AccountSelection"
