"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class LinkTokenCreateRequestUpdateModeEnum(str, Enum):
    UPDATE_CREDENTIALS = "UpdateCredentials"
    REFRESH = "Refresh"
    UPDATE_ACCOUNT_SELECTION = "UpdateAccountSelection"
