"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .linksourcesresponsesource import (
    LinkSourcesResponseSource,
    LinkSourcesResponseSourceTypedDict,
)
from deck_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class LinkSourcesResponseTypedDict(TypedDict):
    sources: NotRequired[List[LinkSourcesResponseSourceTypedDict]]
    r"""List of data sources found."""


class LinkSourcesResponse(BaseModel):
    sources: Optional[List[LinkSourcesResponseSource]] = None
    r"""List of data sources found."""
