"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from deck_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class LinkAccountSelectRequestTypedDict(TypedDict):
    link_token: str
    r"""The link_token, must be provided when calling Link endpoints, for identifying the Link session."""
    accounts: NotRequired[List[str]]
    r"""List of selected accounts"""


class LinkAccountSelectRequest(BaseModel):
    link_token: str
    r"""The link_token, must be provided when calling Link endpoints, for identifying the Link session."""

    accounts: Optional[List[str]] = None
    r"""List of selected accounts"""
