"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from deck_sdk.types import BaseModel
from typing_extensions import TypedDict


class LinkConnectRequestFieldTypedDict(TypedDict):
    field_name: str
    field_value: str


class LinkConnectRequestField(BaseModel):
    field_name: str

    field_value: str
