"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from deck_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class MfaAnswerRequestTypedDict(TypedDict):
    answer: str
    job_guid: NotRequired[str]


class MfaAnswerRequest(BaseModel):
    answer: str

    job_guid: Optional[str] = None
