"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .accesstokenrequest import AccessTokenRequest, AccessTokenRequestTypedDict
from deck_sdk.types import BaseModel
from deck_sdk.utils import FieldMetadata, QueryParamMetadata, RequestMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PostJobsDocumentsListRequestTypedDict(TypedDict):
    job_guid: NotRequired[str]
    access_token_request: NotRequired[AccessTokenRequestTypedDict]


class PostJobsDocumentsListRequest(BaseModel):
    job_guid: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    access_token_request: Annotated[
        Optional[AccessTokenRequest],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None
