"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from deck_sdk.types import BaseModel
from typing import Dict
from typing_extensions import TypedDict


class PostJobsSubmitRequestTypedDict(TypedDict):
    job_code: str
    r"""The job type identifier"""
    input: Dict[str, str]
    r"""Dynamic input object - structure varies by job type"""


class PostJobsSubmitRequest(BaseModel):
    job_code: str
    r"""The job type identifier"""

    input: Dict[str, str]
    r"""Dynamic input object - structure varies by job type"""
