"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from deck_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ProviderTypedDict(TypedDict):
    id: NotRequired[str]
    r"""Unique identifier of the data provider associated to this connectiond"""
    name: NotRequired[str]
    r"""Name of the data source provider to this connection"""


class Provider(BaseModel):
    id: Optional[str] = None
    r"""Unique identifier of the data provider associated to this connectiond"""

    name: Optional[str] = None
    r"""Name of the data source provider to this connection"""
