"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from deck_sdk.types import BaseModel
from typing_extensions import TypedDict


class RawDocumentRequestTypedDict(TypedDict):
    access_token: str
    r"""The access token associated with the Item data is being requested for"""
    document_id: str


class RawDocumentRequest(BaseModel):
    access_token: str
    r"""The access token associated with the Item data is being requested for"""

    document_id: str
