"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from deck_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class RefreshConnectionRequestTypedDict(TypedDict):
    access_token: str
    r"""The access token associated with the Item data is being requested for"""
    account_numbers: NotRequired[List[str]]


class RefreshConnectionRequest(BaseModel):
    access_token: str
    r"""The access token associated with the Item data is being requested for"""

    account_numbers: Optional[List[str]] = None
