"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from deck_sdk.types import BaseModel
from typing_extensions import TypedDict


class SecurityQuestionResponseTypedDict(TypedDict):
    question: str


class SecurityQuestionResponse(BaseModel):
    question: str
