"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from deck_sdk.types import BaseModel
from typing_extensions import TypedDict


class SecurityQuestionAnswerSaveRequestTypedDict(TypedDict):
    link_token: str
    r"""The link_token, must be provided when calling Link endpoints, for identifying the Link session."""
    answer: str


class SecurityQuestionAnswerSaveRequest(BaseModel):
    link_token: str
    r"""The link_token, must be provided when calling Link endpoints, for identifying the Link session."""

    answer: str
