"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from deck_sdk.types import BaseModel
from typing_extensions import TypedDict


class WebhookUpdateRequestTypedDict(TypedDict):
    access_token: str
    r"""The access token associated with the Item data is being requested for"""
    url: str
    r"""The URL of the webhook"""
    is_active: bool
    r"""The status of the webhook. If true, the webhook is active. If false, the webhook is inactive."""


class WebhookUpdateRequest(BaseModel):
    access_token: str
    r"""The access token associated with the Item data is being requested for"""

    url: str
    r"""The URL of the webhook"""

    is_active: bool
    r"""The status of the webhook. If true, the webhook is active. If false, the webhook is inactive."""
