"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from deck_sdk.errors import DeckSDKError
from deck_sdk.types import BaseModel
import httpx
import pydantic
from typing import Optional
from typing_extensions import Annotated


class AlreadyRunningJobResponseErrorData(BaseModel):
    job_id: Annotated[
        str,
        pydantic.Field(
            deprecated="warning: ** DEPRECATED ** - This will be removed in a future release, please migrate away from it as soon as possible."
        ),
    ]
    r"""[Obsolete] Legacy identifier of the job. Use JobGuid instead."""

    job_guid: str
    r"""Unique identifier of the already running job."""

    message: Annotated[
        str,
        pydantic.Field(
            deprecated="warning: ** DEPRECATED ** - This will be removed in a future release, please migrate away from it as soon as possible."
        ),
    ]
    r"""[Obsolete] Legacy message describing the conflict. Use ErrorMessage instead."""

    error_message: str
    r"""A human-readable error message indicating the job is already in progress."""


class AlreadyRunningJobResponseError(DeckSDKError):
    data: AlreadyRunningJobResponseErrorData

    def __init__(
        self,
        data: AlreadyRunningJobResponseErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        self.data = data
